inherit_from:
  - https://raw.githubusercontent.com/clarkology56/.dotfiles/master/default_rubocop_config.yml

inherit_mode:
  merge:
    - Exclude

Layout/LineLength:
  Exclude:
    - "lib/upserv_foundations/helpers/components/**/*.rb"
      
Metrics/AbcSize:
  Exclude:
    - "lib/upserv_foundations/helpers/components/**/*.rb"


Metrics/MethodLength:
  Exclude:
    - "lib/upserv_foundations/helpers/components/**/*.rb"
      
Style/IfUnlessModifier:
  Exclude:
  - "lib/upserv_foundations/helpers/components/**/*.rb"
