inherit_from:
  - https://raw.githubusercontent.com/clarkology56/.dotfiles/master/default_rubocop_config.yml

inherit_mode:
  merge:
    - Exclude

Layout/LineLength:
  Exclude:
    - "app/helpers/global/modal_trigger_attributes_helper.rb"
